<?php
/**
 * Витрина: компоненты и базовые сборки.
 *
 * Файл данных, а не логики: подключается из scripts/migrate.php и
 * возвращает массив. Держится отдельно, потому что сами компоненты
 * и есть данные, а правила вставки - в migrate.php.
 *
 * Ссылки в сборках даны именем компонента, а не его id: id на свежей
 * базе назначает сама БД, а на уже заполненной он указывает на
 * другие строки. Имя у компонента уникально в пределах категории.
 *
 * Названия и описания совпадают с каталогом: иначе после развёртывания
 * с SEED_DATA=1 один и тот же товар лежал бы в каталоге дважды -
 * seed_components.php пропускает по имени и категории, а отличающееся
 * имя прошло бы мимо проверки.
 */

declare(strict_types=1);

return [
    'components' => [
        [
            'name' => 'i3-10100',
            'category_id' => 1,
            'socket_id' => 1,
            'video_core' => 1,
            'tdp' => 65,
            'price' => 5500,
            'manufacturer' => 'Intel',
            'model' => 'i3-10100',
            'description' => 'Intel Core i3-10100 — 4 ядра, 8 потоков, базовая частота 3,1 ГГц (турбо до 3,9 ГГц), кэш 6 МБ, сокет LGA1200. Встроенная графика: Intel UHD Graphics 630.',
            'specs' => '{"lit":true,"cores":4,"threads":8,"base_ghz":3.1,"cache_mb":6,"boost_ghz":3.9}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'i7-12700F',
            'category_id' => 1,
            'socket_id' => 2,
            'video_core' => 0,
            'tdp' => 180,
            'price' => 32599,
            'manufacturer' => 'Intel',
            'model' => 'i7-12700F',
            'description' => 'Intel Core i7-12700F — 20 ядер, 28 потоков, базовая частота 2,1 ГГц (турбо до 4,9 ГГц), кэш 33 МБ, сокет LGA1700. Без встроенной графики.',
            'specs' => '{"lit":false,"cores":20,"threads":28,"base_ghz":2.1,"cache_mb":33,"boost_ghz":4.9}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Ryzen 5 5600G',
            'category_id' => 1,
            'socket_id' => 3,
            'video_core' => 1,
            'tdp' => 65,
            'price' => 19699,
            'manufacturer' => 'AMD',
            'model' => 'Ryzen 5 5600G',
            'description' => 'AMD Ryzen 5 5600G — 6 ядер, 12 потоков, базовая частота 3,9 ГГц (турбо до 4,4 ГГц), кэш 32 МБ, сокет AM4. Встроенная графика: Radeon Vega 8.',
            'specs' => '{"lit":true,"cores":6,"threads":12,"base_ghz":3.9,"cache_mb":32,"boost_ghz":4.4}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'ASRock H410M-HVS R2.0',
            'category_id' => 2,
            'socket_id' => 1,
            'video_core' => null,
            'tdp' => null,
            'price' => 2100,
            'manufacturer' => 'ASRock',
            'model' => 'H410M-HVS R2.0',
            'description' => 'ASRock H410M-HVS R2.0 — материнская плата для процессоров Intel 10-го поколения, сокет LGA1200. Чипсет H410, 2 слота DDR4, форм-фактор Micro-ATX.',
            'specs' => '{"chipset":"H410","m2_slots":1,"ram_slots":2}',
            'ram_type' => 'DDR4',
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => 'Micro-ATX',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'ASRock Z690 Phantom Gaming 4',
            'category_id' => 2,
            'socket_id' => 2,
            'video_core' => null,
            'tdp' => null,
            'price' => 13999,
            'manufacturer' => 'ASRock',
            'model' => 'Z690 Phantom Gaming 4',
            'description' => 'ASRock Z690 Phantom Gaming 4 — материнская плата для процессоров Intel 11-го и 12-го поколения, сокет LGA1700. Чипсет Z690, 4 слота DDR5, форм-фактор ATX.',
            'specs' => '{"chipset":"Z690","ram_slots":4}',
            'ram_type' => 'DDR5',
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => 'ATX',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'ASRock A520M Pro4',
            'category_id' => 2,
            'socket_id' => 3,
            'video_core' => null,
            'tdp' => null,
            'price' => 6799,
            'manufacturer' => 'ASRock',
            'model' => 'A520M Pro4',
            'description' => 'ASRock A520M Pro4 — материнская плата для процессоров AMD сокета AM4, сокет AM4. Чипсет A520, 2 слота DDR4, форм-фактор Micro-ATX.',
            'specs' => '{"chipset":"A520","ram_slots":2}',
            'ram_type' => 'DDR4',
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => 'Micro-ATX',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'PowerColor AMD Radeon RX 6500 XT ITX',
            'category_id' => 3,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 28499,
            'manufacturer' => 'PowerColor',
            'model' => 'AMD Radeon RX 6500 XT ITX',
            'description' => 'PowerColor AMD Radeon RX 6500 XT ITX — видеокарта с 4 ГБ GDDR6, кристалл Navi 23. Рекомендуемый блок питания от 400 Вт.',
            'specs' => '{"chip":"Navi 23","psu_req_w":400}',
            'ram_type' => null,
            'capacity_gb' => 4,
            'frequency_mhz' => null,
            'memory_type' => 'GDDR6',
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'GIGABYTE GeForce RTX 3080 GAMING OC',
            'category_id' => 3,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 120099,
            'manufacturer' => 'Gigabyte',
            'model' => 'GeForce RTX 3080 GAMING OC',
            'description' => 'Gigabyte GeForce RTX 3080 GAMING OC — видеокарта с 10 ГБ GDDR6X, кристалл GA102. Рекомендуемый блок питания от 750 Вт.',
            'specs' => '{"chip":"GA102","psu_req_w":750}',
            'ram_type' => null,
            'capacity_gb' => 10,
            'frequency_mhz' => null,
            'memory_type' => 'GDDR6X',
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Patriot Signature Line 4gbx2',
            'category_id' => 4,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 2599,
            'manufacturer' => 'Patriot',
            'model' => 'Signature Line 4gbx2',
            'description' => 'Patriot Signature Line 4gbx2 — комплект оперативной памяти 8 ГБ из 2 модулей, DDR4 на 3200 МГц с таймингами CL16.',
            'specs' => '{"modules":2,"timings":"CL16","voltage":1.35}',
            'ram_type' => 'DDR4',
            'capacity_gb' => 8,
            'frequency_mhz' => 3200,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'A-Data XPG Spectrix D60G RGB 16gbx2',
            'category_id' => 4,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 15999,
            'manufacturer' => 'A-Data',
            'model' => 'XPG Spectrix D60G RGB 16gbx2',
            'description' => 'A-Data XPG Spectrix D60G RGB 16gbx2 — комплект оперативной памяти 32 ГБ из 2 модулей, DDR4 на 3200 МГц с таймингами CL16.',
            'specs' => '{"modules":2,"timings":"CL16","voltage":1.35}',
            'ram_type' => 'DDR4',
            'capacity_gb' => 32,
            'frequency_mhz' => 3200,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Kingston FURY Beast Black 4gbx4',
            'category_id' => 4,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 9999,
            'manufacturer' => 'Kingston',
            'model' => 'FURY Beast Black 4gbx4',
            'description' => 'Kingston FURY Beast Black 4gbx4 — комплект оперативной памяти 16 ГБ из 4 модулей, DDR4 на 3200 МГц с таймингами CL16.',
            'specs' => '{"modules":4,"timings":"CL16","voltage":1.35}',
            'ram_type' => 'DDR4',
            'capacity_gb' => 16,
            'frequency_mhz' => 3200,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Cougar VTE400',
            'category_id' => 5,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 3199,
            'manufacturer' => 'Cougar',
            'model' => 'VTE400',
            'description' => 'Cougar VTE400 — блок питания мощностью 400 Вт. Форм-фактор ATX.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => 400,
            'interface' => null,
            'form_factor' => 'ATX',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Cougar GEC 650',
            'category_id' => 5,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 5711,
            'manufacturer' => 'Cougar',
            'model' => 'GEC 650',
            'description' => 'Cougar GEC 650 — блок питания мощностью 650 Вт с сертификатом 80+ Bronze. Форм-фактор ATX. Немодульный.',
            'specs' => '{"cert":"80+ Bronze","modular":"non-modular"}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => 650,
            'interface' => null,
            'form_factor' => 'ATX',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Cougar GX 1050W',
            'category_id' => 5,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 12499,
            'manufacturer' => 'Cougar',
            'model' => 'GX 1050W',
            'description' => 'Cougar GX 1050W — блок питания мощностью 1050 Вт. Форм-фактор ATX.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => 1050,
            'interface' => null,
            'form_factor' => 'ATX',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'AeroCool Cylon White',
            'category_id' => 6,
            'image' => '/assets/images/cases/cylonw.png',
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 3799,
            'manufacturer' => 'AeroCool',
            'model' => 'Cylon White',
            'description' => 'AeroCool Cylon White — корпус для настольного компьютера, форм-фактор Mid-Tower.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => 'Mid-Tower',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'MONTECH FIGHTER 500',
            'category_id' => 6,
            'image' => '/assets/images/cases/fighter500.png',
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 4799,
            'manufacturer' => 'MONTECH',
            'model' => 'FIGHTER 500',
            'description' => 'MONTECH FIGHTER 500 — корпус для настольного компьютера, форм-фактор Mid-Tower.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => 'Mid-Tower',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Thermaltake View 71 Tempered Glass SNOW Edition RGB',
            'category_id' => 6,
            'image' => '/assets/images/cases/view71.png',
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 25349,
            'manufacturer' => 'Thermaltake',
            'model' => 'View 71 Tempered Glass SNOW Edition RGB',
            'description' => 'Thermaltake View 71 Tempered Glass SNOW Edition RGB — корпус для настольного компьютера, форм-фактор Mid-Tower.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => 'Mid-Tower',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'DEEPCOOL Gamma Archer',
            'category_id' => 7,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => 95,
            'price' => 799,
            'manufacturer' => 'DeepCool',
            'model' => 'Gamma Archer',
            'description' => 'DeepCool Gamma Archer — башенный воздушный кулер высотой 148 мм. Подходит для процессоров Intel и AMD.',
            'specs' => '{"sockets":["LGA1200","LGA1700","AM4"],"height_mm":148}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => 'Air',
        ],
        [
            'name' => 'DEEPCOOL GAMMAXX 300',
            'category_id' => 7,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => 130,
            'price' => 1399,
            'manufacturer' => 'DeepCool',
            'model' => 'GAMMAXX 300',
            'description' => 'DeepCool GAMMAXX 300 — башенный воздушный кулер высотой 150 мм. Подходит для процессоров Intel и AMD.',
            'specs' => '{"height_mm":150}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => 'Air',
        ],
        [
            'name' => 'DEEPCOOL GAMMAXX L240T WHITE',
            'category_id' => 7,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => 200,
            'price' => 4699,
            'manufacturer' => 'DeepCool',
            'model' => 'GAMMAXX L240T WHITE',
            'description' => 'DeepCool GAMMAXX L240T WHITE — система жидкостного охлаждения с радиатором 240 мм и помпой в блоке.',
            'specs' => '{"sockets":["LGA1200","LGA1700","AM4"],"radiator_mm":240}',
            'ram_type' => null,
            'capacity_gb' => null,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => null,
            'cooler_type' => 'AIO',
        ],
        [
            'name' => 'Western Digital Blue 2tb',
            'category_id' => 8,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 4999,
            'manufacturer' => 'Western Digital',
            'model' => 'Blue 2tb',
            'description' => 'Western Digital Blue 2tb — жёсткий диск для настольного компьютера. Скорость вращения 5400 об/мин, SATA.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => 2000,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => null,
            'form_factor' => null,
            'rpm' => 5400,
            'cooler_type' => null,
        ],
        [
            'name' => 'Apacer AST280 M.2 240gb',
            'category_id' => 9,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 2199,
            'manufacturer' => 'Apacer',
            'model' => 'AST280 M.2 240gb',
            'description' => 'Apacer AST280 M.2 240gb — твердотельный накопитель на 240 ГБ, интерфейс M.2.',
            'specs' => 'null',
            'ram_type' => null,
            'capacity_gb' => 240,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => 'M.2',
            'form_factor' => 'M.2',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Kingston NV1 M.2 500gb',
            'category_id' => 9,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 4550,
            'manufacturer' => 'Kingston',
            'model' => 'NV1 M.2 500gb',
            'description' => 'Kingston NV1 M.2 500gb — твердотельный накопитель на 500 ГБ, интерфейс M.2. Скорость чтения до 3100 МБ/с, записи до 2100 МБ/с, память TLC, ресурс записи 160 ТБ.',
            'specs' => '{"tbw":160,"nand":"TLC","read_mbs":3100,"write_mbs":2100}',
            'ram_type' => null,
            'capacity_gb' => 500,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => 'M.2',
            'form_factor' => 'M.2',
            'rpm' => null,
            'cooler_type' => null,
        ],
        [
            'name' => 'Samsung 980 M.2 500gb',
            'category_id' => 9,
            'socket_id' => null,
            'video_core' => null,
            'tdp' => null,
            'price' => 8899,
            'manufacturer' => 'Samsung',
            'model' => '980 M.2 500gb',
            'description' => 'Samsung 980 M.2 500gb — твердотельный накопитель на 500 ГБ, интерфейс M.2. Скорость чтения до 3500 МБ/с, записи до 3000 МБ/с, память TLC, ресурс записи 300 ТБ.',
            'specs' => '{"tbw":300,"nand":"TLC","read_mbs":3500,"write_mbs":3000}',
            'ram_type' => null,
            'capacity_gb' => 500,
            'frequency_mhz' => null,
            'memory_type' => null,
            'wattage' => null,
            'interface' => 'M.2',
            'form_factor' => 'M.2',
            'rpm' => null,
            'cooler_type' => null,
        ],
    ],

    'assemblies' => [
        [
            'name' => 'EinTech',
            'tag' => 'Офис',
            'cpu_id' => 'i3-10100',
            'motherboard_id' => 'ASRock H410M-HVS R2.0',
            'gpu_id' => null,
            'ram_id' => 'Patriot Signature Line 4gbx2',
            'case_id' => 'AeroCool Cylon White',
            'cooler_id' => 'DEEPCOOL Gamma Archer',
            'power_supply_id' => 'Cougar VTE400',
            'ssd_id' => 'Apacer AST280 M.2 240gb',
            'ssd_2_id' => null,
            'hdd_id' => null,
            'dvd_id' => null,
            'price' => 30000,
        ],
        [
            'name' => 'Eternal',
            'tag' => 'Игры',
            'cpu_id' => 'Ryzen 5 5600G',
            'motherboard_id' => 'ASRock A520M Pro4',
            'gpu_id' => 'PowerColor AMD Radeon RX 6500 XT ITX',
            'ram_id' => 'Kingston FURY Beast Black 4gbx4',
            'case_id' => 'MONTECH FIGHTER 500',
            'cooler_id' => 'DEEPCOOL GAMMAXX 300',
            'power_supply_id' => 'Cougar GEC 650',
            'ssd_id' => 'Kingston NV1 M.2 500gb',
            'ssd_2_id' => null,
            'hdd_id' => null,
            'dvd_id' => null,
            'price' => 105000,
        ],
        [
            'name' => 'Magic Workbench',
            'tag' => 'Про',
            'cpu_id' => 'i7-12700F',
            'motherboard_id' => 'ASRock Z690 Phantom Gaming 4',
            'gpu_id' => 'GIGABYTE GeForce RTX 3080 GAMING OC',
            'ram_id' => 'A-Data XPG Spectrix D60G RGB 16gbx2',
            'case_id' => 'Thermaltake View 71 Tempered Glass SNOW Edition RGB',
            'cooler_id' => 'DEEPCOOL GAMMAXX L240T WHITE',
            'power_supply_id' => 'Cougar GX 1050W',
            'ssd_id' => 'Samsung 980 M.2 500gb',
            'ssd_2_id' => null,
            'hdd_id' => 'Western Digital Blue 2tb',
            'dvd_id' => null,
            'price' => 340000,
        ],
    ],
];
